-- Supabase CRM – Initial schema
-- Run in Supabase SQL Editor (Dashboard > SQL Editor)
-- Tables: users (extend auth.users), clients, interactions, email_templates, calling_scripts

-- Optional: public.users profile (links to auth.users; create after enabling Auth)
-- create table if not exists public.users (
--   id uuid primary key references auth.users(id) on delete cascade,
--   email text,
--   role text not null default 'user' check (role in ('user', 'manager', 'admin')),
--   created_at timestamptz default now(),
--   updated_at timestamptz default now()
-- );

-- Clients
create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  client_name text not null,
  address text,
  email text,
  status text not null default 'Intro Email Sent' check (status in (
    'Intro Email Sent', 'Follow-up Email Sent', 'Client Responded',
    'No Response from Client', 'Client Acquired'
  )),
  user_id uuid references auth.users(id) on delete set null
);

-- Interactions (email/call log per client)
create table if not exists public.interactions (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  client_id bigint not null references public.clients(id) on delete cascade,
  type text not null check (type in ('email', 'call')),
  notes text,
  status_at_time text,
  created_by uuid references auth.users(id) on delete set null
);

-- Email templates (for Email Generator)
create table if not exists public.email_templates (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null,
  content text not null
);

-- Calling scripts (stage-based, read-only)
create table if not exists public.calling_scripts (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  stage text not null,
  stage_order int default 0,
  name text,
  content text
);

-- RLS: enable on all tables
alter table public.clients enable row level security;
alter table public.interactions enable row level security;
alter table public.email_templates enable row level security;
alter table public.calling_scripts enable row level security;

-- Policies (adjust for your roles; example: user sees own clients, manager sees team, admin sees all)
-- Example: allow authenticated users to read/write clients (tune per role in your app)
create policy "Allow authenticated read clients" on public.clients for select to authenticated using (true);
create policy "Allow authenticated insert clients" on public.clients for insert to authenticated with check (true);
create policy "Allow authenticated update clients" on public.clients for update to authenticated using (true);

create policy "Allow authenticated read interactions" on public.interactions for select to authenticated using (true);
create policy "Allow authenticated insert interactions" on public.interactions for insert to authenticated with check (true);

create policy "Allow authenticated read email_templates" on public.email_templates for select to authenticated using (true);
create policy "Allow authenticated read calling_scripts" on public.calling_scripts for select to authenticated using (true);

-- Optional: grant usage for anon if you use anon key with JWT
-- grant usage on schema public to anon;
-- grant select, insert, update on public.clients to authenticated;
-- grant select, insert on public.interactions to authenticated;
-- grant select on public.email_templates, public.calling_scripts to authenticated;
